[assistant]
name="John"

[defaults]
llm="Qwen2-72B-Instruct"
code="CodeQwen1.5-7b"
vision="MiniCPM Llama3-V-2.5"

[defaults.src]
llm="orionai/llama-3.1-70b-demo"
code="Qwen/CodeQwen1.5-7b-Chat-demo"
vision="openbmb/MiniCPM-Llama3-V-2_5"