[assistant]
name="Basil"
personality="You have a kind, deterministic and professional attitude towards your work and respond in a formal, yet casual manner."

[defaults]
llm="Llama-3.1-405B-Instruct"
code="CodeQwen1.5-7b"
vision="MiniCPM-Llama3-V-2.5"

[defaults.src]
llm="Nymbo/Llama-3.1-405B-Instruct"
code="Qwen/CodeQwen1.5-7b-Chat-demo"
vision="openbmb/MiniCPM-Llama3-V-2_5"