
ephemeral: false

profile:
    name: {name}

openmacro:
    name: Basil
    personality: Yeah
    messages: []
    verbose: false
    local: false
    telemetry: false

paths:
    prompts: "{root}/prompts"
    extensions: "{root}/extensions"
    ltm: "{root}/memories"

breakers:
    - the task is done.
    - the conversation is done.

extensions:
    browser:
        headless: true
        engine: google
    email:
        email: amor.budiyanto@gmail.com
        password: password

safeguards:
    timeout: 16
    auto_run: true
    auto_install: true





